# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(cmake/)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
    types_or: [c++, c, qml]
  - id: end-of-file-fixer
    types_or: [c++, c, qml]
  - id: check-merge-conflict
  - id: mixed-line-ending
    types_or: [c, c++, qml]
    args: ['--fix=lf']
    description: Forces to replace line ending by the UNIX 'lf' character
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.5
  hooks:
  - id: clang-format
    types_or: [c++, c]
