#include "JT808/MessageIds.h"
#include <string>

std::string JT808::MessageIdString(MessageIds id)
{
    switch (id) {
    case TerminalGeneralResponseMsgId:
        return "TerminalGeneralResponse";
    case TerminalHeartBeatMsgId:
        return "TerminalHeartBeat";
    case TerminalLogoutMsgId:
        return "TerminalLogout";
    case TerminalRegistrationMsgId:
        return "TerminalRegistration";
    case TerminalAuthenticationMsgId:
        return "TerminalAuthentication";
    case TerminalParameterQueryResponseMsgId:
        return "TerminalParameterQueryResponse";
    case TerminalPropertiesQueryResponseMsgId:
        return "TerminalPropertiesQueryResponse";
    case TerminalUpgradePackageResultMsgId:
        return "TerminalUpgradePackageResult";
    case LocationInformationReportMsgId:
        return "LocationInformationReport";
    case LocationInformationQueryResponseMsgId:
        return "LocationInformationQueryResponse";
    case EventReportMsgId:
        return "EventReport";
    case QuestionResponseMsgId:
        return "QuestionResponse";
    case InformationServiceCancelMsgId:
        return "InformationServiceCancel";
    case VehicleControlResponseMsgId:
        return "VehicleControlResponse";
    case DrivingRecordDataUploadMsgId:
        return "DrivingRecordDataUpload";
    case ElectronicWaybillReportMsgId:
        return "ElectronicWaybillReport";
    case DriverIdentityInformationReportMsgId:
        return "DriverIdentityInformationReport";
    case LocationDataBulkUploadMsgId:
        return "LocationDataBulkUpload";
    case CANBusDataUploadMsgId:
        return "CANBusDataUpload";
    case MultimediaEventInformationUploadMsgId:
        return "MultimediaEventInformationUpload";
    case MultimediaDataUploadMsgId:
        return "MultimediaDataUpload";
    case StoredMultimediaDataRetrievalResponseMsgId:
        return "StoredMultimediaDataRetrievalResponse";
    case ImmediateCameraCaptureCommandResponseMsgId:
        return "ImmediateCameraCaptureCommandResponse";
    case UpwardDataTransmissionMsgId:
        return "UpwardDataTransmission";
    case DataCompressionReportMsgId:
        return "DataCompressionReport";
    case TerminalRSAPublicKeyMsgId:
        return "TerminalRSAPublicKey";
    case PlatformGeneralResponseMsgId:
        return "PlatformGeneralResponse";
    case SubPackageRetransmissionRequestMsgId:
        return "SubPackageRetransmissionRequest";
    case TerminalRegistrationResponseMsgId:
        return "TerminalRegistrationResponse";
    case TerminalParameterSettingMsgId:
        return "TerminalParameterSetting";
    case TerminalParameterQueryMsgId:
        return "TerminalParameterQuery";
    case TerminalControlMsgId:
        return "TerminalControl";
    case TerminalSpecificParameterQueryMsgId:
        return "TerminalSpecificParameterQuery";
    case TerminalPropertiesQueryMsgId:
        return "TerminalPropertiesQuery";
    case TerminalUpgradePackageMsgId:
        return "TerminalUpgradePackage";
    case LocationInformationQueryMsgId:
        return "LocationInformationQuery";
    case TemporaryLocationTrackingControlMsgId:
        return "TemporaryLocationTrackingControl";
    case ManualAlarmConfirmationMsgId:
        return "ManualAlarmConfirmation";
    case TextMessageDispatchMsgId:
        return "TextMessageDispatch";
    case EventSettingMsgId:
        return "EventSetting";
    case QuestionDispatchMsgId:
        return "QuestionDispatch";
    case InformationServiceMenuSettingMsgId:
        return "InformationServiceMenuSetting";
    case InformationServiceMsgId:
        return "InformationService";
    case CallbackPhoneMsgId:
        return "CallbackPhone";
    case PhoneBookSettingMsgId:
        return "PhoneBookSetting";
    case VehicleControlMsgId:
        return "VehicleControl";
    case SettingCircularAreaMsgId:
        return "SettingCircularArea";
    case DeletingCircularAreaMsgId:
        return "DeletingCircularArea";
    case SettingRectangularAreaMsgId:
        return "SettingRectangularArea";
    case DeletingRectangularAreaMsgId:
        return "DeletingRectangularArea";
    case SettingPolygonAreaMsgId:
        return "SettingPolygonArea";
    case DeletingPolygonAreaMsgId:
        return "DeletingPolygonArea";
    case SettingRouteMsgId:
        return "SettingRoute";
    case DeletingRouteMsgId:
        return "DeletingRoute";
    case DrivingRecordDataCollectionCommandMsgId:
        return "DrivingRecordDataCollectionCommand";
    case DrivingRecordParameterCommandMsgId:
        return "DrivingRecordParameterCommand";
    case DriverIdentityInformationRequestMsgId:
        return "DriverIdentityInformationRequest";
    case MultimediaDataUploadResponseMsgId:
        return "MultimediaDataUploadResponse";
    case ImmediateCameraCaptureCommandMsgId:
        return "ImmediateCameraCaptureCommand";
    case StoredMultimediaDataRetrievalMsgId:
        return "StoredMultimediaDataRetrieval";
    case StoredMultimediaDataUploadCommandMsgId:
        return "StoredMultimediaDataUploadCommand";
    case AudioRecordingStartCommandMsgId:
        return "AudioRecordingStartCommand";
    case SingleStoredMultimediaItemRetrievalUploadCommandMsgId:
        return "SingleStoredMultimediaItemRetrievalUploadCommand";
    case DownwardDataTransmissionMsgId:
        return "DownwardDataTransmission";
    case PlatformRSAPublicKeyMsgId:
        return "PlatformRSAPublicKey";
    default:
        return {};
    }
}
