name: C/C++ CI

on:
  push:
    branches:
      - dev*
    tags:
      - v*
  pull_request:
    branches:
      - dev
      - main
    types: [opened, reopened, synchronize]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          run_tests: ON

